### PR TITLE
Update Travis configuration

### PR DESCRIPTION
**Pull request by pali**
* Use both gcc and clang compilers
* Compile with -fwrapv and -fsanitize=address
* Compile in both 32 and 64 modes for x86 systems
* Cross compile for little endian arm and big endian powerpc
* Run cross compiled binaries in qemu

### CODE REVIEW

**Comment by pali** [comment]
Seems that Travis does not update build status on github page for dosfstools organization. Probably @andreasbombe as admin of dosfstools organization needs to re-enable/re-approve it.

Here is build link for this pull request: https://travis-ci.org/dosfstools/dosfstools/builds/481711836

Build & test with clang is failing due to some memory problems in dosfstools code itself.

**Comment by pali** [comment]
Now build status on github is updated.

**Comment by pali** [comment]
Now tests are passing.

**Comment by fstirlitz** [comment]
Why `-fwrapv`? Wouldn't actually *catching* overflow errors in CI tests (i.e. `-ftrapv`, or `-fsanitize=signed-integer-overflow`, or outright `-fsanitize=undefined`) be better?

**Comment by pali** [comment]
`-fsanitize` does not work for static builds and it is quite new option in gcc. If you have a way how to improve CI testing, feel free to create a pull request.

**Pull request merged**
