### PR TITLE
mkfs.fat: Fix handling of FAT32 backup and info sectors

### PR DESCRIPTION
**Pull request by pali**
Fixes: https://github.com/dosfstools/dosfstools/issues/74
Fixes: https://github.com/dosfstools/dosfstools/issues/110

### CODE REVIEW

**Comment by saproj** [comment]
This pull request introduces more changes than needed to fix #74. One-line change fixes it:
`		(reserved_sectors >= 3) ? reserved_sectors - 1 : 0;`
Other (quite sophisticated) changes to code and a manpage addition can be suggested separately.

Let me point out that this so easily fixable bug #74 has been open for more than a year and since then at least one more person (me) stumbled on it.

**Comment by pali** [comment]
> Is a backup of the info sector actually needed?

Yes, it is required FAT specification (fatgen103.pdf).

So implementation of FAT which is compliance with that specification may handle such FS as in inconsistant state.

If something is written in specification you should really follow it unless you have a very strong argument against (e.g. clean mistake in specification). Otherwise there would be lot of "incompatible" implementations and specification is there to ensure that all implementations would be compatible.

> Does any program look for it?

I do not know.

I just checked that some versions of format.exe on Windows really put there backup of info sector. And because MS's Windows implementation is basically "normative" (FAT is their product) we should follow it there.

> but the info sector is just a cache which can be readily regenerated by scanning the FAT (even though may take some time).

I agree with you. What is the real reason I do not know. You would have to ask authors of specification to get reason.

I can imagine that backup info sector may be used when main one is broken and FAT volume is really huge with small cluster size. This would lead to big FAT table and reconstruction of "cache" in info sector can take too much time. So access to backup is faster.

**Comment by fstirlitz** [comment]
That surprised me, because I have that document and couldn't find it there before. But indeed there it is, page 22. In fact I should have been asking why not also make a copy of the third sector… though I guess it's because `mkfs.fat` puts zeroes there anyway.

> I can imagine that backup info sector may be used when main one is broken and FAT volume is really huge with small cluster size. This would lead to big FAT table and reconstruction of "cache" in info sector can take too much time. So access to backup is faster.

I don't think so. Page 12 of the same specification suggests that the backup is not meant to be continuously kept in sync with the active copy. I also took a look at one FAT32 volume I have (used by a VM), and there is indeed a stale copy of the FSINFO sector there (and a copy of sector 2 as well). So it seems the backup is mostly meant to keep data related to disk layout, which is unlikely to change throughout the lifetime of the file system; given that, the FSINFO backup is unlikely to be relied on anyway.

But spec is spec, I guess.

**Comment by pali** [comment]
> In fact I should have been asking why not also make a copy of the third sector

We both agree that fatgen103.pdf specification is a mess.

First some facts which I think should be clear:

First part of FS is Reserved Region which length is BPB_RsvdSecCnt sectors. Reserved Region starts at sector 0. At sector 0 is stored Boot Sector, at sector 1 is stored FSInfo Sector and at sector 6 is stored Backup Boot Sector.

And then in fatgen103.pdf is written:
>  Note that starting at the BPB_BkBootSec sector is a complete boot record. The Microsoft FAT32 “boot sector” is actually three 512-byte sectors long. There is a copy of all three of these sectors starting at the BPB_BkBootSec sector. A copy of the FSInfo sector is also there

My understanding of this section is following: Boot code must be stored in Reserved Region and must starts at sector 0. Microsoft FAT32 implementation uses boot code with is 3 sectors long. But other implementations are free to have boot code longer or smaller. By complete boot record I understand that boot code which spans more sectors and starts at sector 0. And copy of complete boot record (therefore full boot code) must starts at BPB_BkBootSec sector (6) and continue to next sectors. And into specification wrote that `all three of these sectors` because they referring to their 3 sectors implementation. Other implementations may be larger/smaller. And `A copy of the FSInfo sector is also there` I understand as emphasis of the fact that FSInfo sector is immediately after Boot sector and if you are copying first 3 sectors you would copy also second sector.

As mkfs.fat's boot code is 1 sector long, plus required FSInfo sector which needs to be also there, mkfs.fat `complete boot record` would be only 2 sectors long.

But if you have different understanding of that specification and you thinks that 3rd sector needs to be copied, then we can say it is already done. 3rd sector for mkfs.fat is empty (we do not use it) and because by default Reserved Area is 32 sectors, we have a copy of 3rd sector stored on 8th sector (both are empty, zeroed).

And what is the reason? I really do not know. We can just speculate. Maybe even MS do not know... Another speculation: MS boot code 3 sectors long and second sector (sector 1) is by requirement FSInfo Sector. So their bootloader is stored on sector 0 and sector 2. With possiblity that other implementation (or even MS in future) could have longer bootloader stored on more sectors (therefore on 3, 4, 5...). And to simplify restoration process when sector 0 is broken, just copy from starting sector 6 all boot code (6, 7, 8, ...) to starting sector 0 (0, 1, 2, ...) without need to specially handle and skip sector 7 which is backup copy of FSInfo Sector. And maybe MS did not think that somebody wrote bootloader which fit into one sector and does not need them more...

**Pull request merged**
