### PR TITLE
Remove logic related to FAT_NO_83NAME

### PR DESCRIPTION
**Pull request by msuhanov**
And rename `lcase` to `ntbyte`.

Fixes: https://github.com/dosfstools/dosfstools/issues/170.

### CODE REVIEW

**Comment by pali** [comment]
Perfect, thank you for this pull request.

Could you include your test case into dosfstools test suite which caused this issue?

**Comment by msuhanov** [comment]
Okay, will do soon.

**Comment by msuhanov** [comment]
Done. The images were created in Windows 11, then modified to introduce corruption and remove proprietary boot code.

**Review by pali — APPROVED** [review]
Ok! Tests are passing on CI. And manually running new tests without this fsck change are (correctly) failing.

**Comment by pali** [comment]
Merged!

Not sure, but maybe adding some documentation or defines for these bits into linux kernel file https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/uapi/linux/msdos_fs.h could be useful?

**Pull request merged**
