### PR TITLE
mkfs.fat: Aproximate cluster_size calculation for non 512 sects disks

### PR DESCRIPTION
**Pull request by yarda**
Fixes: 111

Signed-off-by: Jaroslav Škarvada <jskarvad@redhat.com>

### CODE REVIEW

**Comment by yarda** [comment]
This fixes #111

**Comment by pali** [comment]
Hi! I have semi-prepared patches which change logic for calculation of cluser size which are block size independent. But due to slow progress of reviewing my other 10+ opened pull requests, I decided to not push new patches... (plus they depeneds on existing opened pull requests).

**Comment by pali** [comment]
Now I pushed those old patches to pull request https://github.com/dosfstools/dosfstools/pull/153 please check if it fixes this issue.

**Comment by pali** [comment]
@yarda: Can you test #153? Now it contains also test for 600MB large 4K disk and it passes.

**Comment by yarda** [comment]
Sorry for delay, I will test it

**Comment by yarda** [comment]
> Sorry for delay, I will test it

I am now trying to get some machine with 4K disk.

**Comment by yarda** [comment]
It seems the calculation is the same (the formula is written different, but more legible way). I also tested the code on the affected system where it previously failed (without the patch) and it works now, so thanks and closing the PR.

**Comment by pali** [comment]
Ok!

**Pull request closed without merging**
