### PR TITLE
Add OSX support

### PR DESCRIPTION
**Pull request by Noltari**
Signed-off-by: Álvaro Fernández Rojas <noltari@gmail.com>

### CODE REVIEW

**Comment by andreasbombe** [comment]
Thank you. I have already planned to remove the Linux dependencies. However, I plan to do my own data structure definitions rather than just copy in the Linux include files which were just used way back when by someone to save some typing work.

This means I will not pull this patch as-is, but I welcome you to adapt your fixes after I've gotten rid of the Linux include dependencies.

**Comment by Noltari** [comment]
Ok, I'm looking forward to that changes and I will be glad to help you if I can.
I personally need dosfstools to be compatible with OS X in order to be able to build OpenWrt for the Raspberry PI on OS X.

**Comment by Noltari** [comment]
BTW, what about something like this? https://github.com/Noltari/dosfstools/commit/f91225c9e48de1ff339193991ca5e1acacbc6f7f

**Comment by Noltari** [comment]
Closing, see https://github.com/dosfstools/dosfstools/pull/4, https://github.com/dosfstools/dosfstools/pull/5 and https://github.com/dosfstools/dosfstools/pull/6

OS X support will be added on another PR once those PR are merged.

**Pull request closed without merging**
